--------------------------------------------------------
--  DDL for View KLIENT_NAJWIECEJ_PROJEKTOW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ZUR"."KLIENT_NAJWIECEJ_PROJEKTOW" ("NAZWA", "COUNT(PROJEKT.KLIENT)") AS 
  SELECT "NAZWA","COUNT(PROJEKT.KLIENT)" FROM (
SELECT KLIENT.NAZWA, COUNT(PROJEKT.KLIENT) FROM KLIENT
LEFT JOIN PROJEKT ON KLIENT.ID=PROJEKT.KLIENT
GROUP BY KLIENT.NAZWA
ORDER BY COUNT(PROJEKT.KLIENT) DESC
)
WHERE ROWNUM <= 1
;
