--------------------------------------------------------
--  DDL for View NAJCIEZSZE_ZADANIE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ZUR"."NAJCIEZSZE_ZADANIE" ("NAZWISKO", "NAZWA_PROJEKTU", "OPIS_ZADANIA", "CZAS") AS 
  SELECT "NAZWISKO","NAZWA_PROJEKTU","OPIS_ZADANIA","CZAS" FROM (
SELECT NAZWISKO, PROJEKT.NAZWA AS NAZWA_PROJEKTU, ZADANIE.OPIS AS OPIS_ZADANIA, ZADANIE.CZAS FROM PRACOWNIK
LEFT JOIN ZADANIE ON PRACOWNIK.ID=ZADANIE.PRACOWNIK
LEFT JOIN PROJEKT ON ZADANIE.PROJEKT=PROJEKT.ID
ORDER BY ZADANIE.CZAS DESC
)
WHERE ROWNUM <= 1
;
