--------------------------------------------------------
--  DDL for View NAJEFEKTYWNIEJ_PRACUJACY
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ZUR"."NAJEFEKTYWNIEJ_PRACUJACY" ("NAZWISKO", "SUM(ZADANIE.CZAS)") AS 
  SELECT "NAZWISKO","SUM(ZADANIE.CZAS)" FROM (
SELECT NAZWISKO, SUM(ZADANIE.CZAS) FROM PRACOWNIK
LEFT JOIN ZADANIE ON PRACOWNIK.ID=ZADANIE.PRACOWNIK
GROUP BY NAZWISKO
ORDER BY SUM(ZADANIE.CZAS) DESC
)
WHERE ROWNUM <= 3
;
