REM INSERTING into ZUR.PRACOWNIK
SET DEFINE OFF;
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('2','Agnesse','Mulqueen','1','3','9312118471','amulqueen1@blog.com','Finance');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('6','Christoph','McVane','5','7','8729972086','cmcvane5@github.io','Basic Industries');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('7','Hulda','Plum','3','5','837823625','hplum6@newsvine.com','Finance');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('8','Alf','Krates','2','8','1096280329','akrates7@twitpic.com','Finance');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('9','Hieronymus','Widdows','2','9','1547168978','hwiddows8@devhub.com','Finance');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('10','Jami','Casellas','4','9','7979526740','jcasellas9@sun.com','Consumer Services');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('11','Nat','Kerin','5','10','2274826218','nkerina@google.nl','Consumer Services');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('12','Lexie','Dreinan','5','1','9349709171','ldreinanb@amazon.de','Consumer Services');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('15','Ashla','Denslow','3','13','3096941521','adenslowe@europa.eu','Finance');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('16','Sharity','Huzzey','3','15','1207084425','shuzzeyf@vinaora.com','Consumer Services');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('20','Damiano','Steger','2','4','8573392703','dstegerj@wp.com','Technology');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('1','Valentina','Emery','1','1','2168797692','vemery0@google.com','Health Care');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('5','Liam','Vokes','1','6','8342762599','lvokes4@issuu.com','Basic Industries');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('18','Gordan','Terron','5','4','7017748212','gterronh@state.gov','Health Care');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('19','Dalila','Eayres','4','14','391192973','deayresi@rediff.com','Health Care');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('3','Nola','Balas','2','2','3280962196','nbalas2@sciencedaily.com','Capital Goods');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('4','Tedi','Fydoe','4','4','7807928050','tfydoe3@japanpost.jp','Finance');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('13','Michel','Rippin','2','11','8282422177','mrippinc@biblegateway.com','Capital Goods');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('14','Jeddy','Danilenko','1','12','1688587691','jdanilenkod@disqus.com','Health Care');
Insert into ZUR.PRACOWNIK (ID,IMIE,NAZWISKO,ODDZIAL,PROJEKT,TELEFON,EMAIL,STANOWISKO) values ('17','Gamaliel','Kean','4','15','8774122649','gkeang@si.edu','Consumer Services');
