REM INSERTING into ZUR.ZADANIE
SET DEFINE OFF;
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('1','7','11','Contrast phlebogram NOS',to_date('17/09/22','RR/MM/DD'),'205');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('2','1','16','Lap lys periren/uret adh',to_date('14/07/10','RR/MM/DD'),'126');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('3','9','17','Endo emb hd/nk,bare coil',to_date('13/12/16','RR/MM/DD'),'173');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('4','8','17','Reattach amputated ear',to_date('16/05/30','RR/MM/DD'),'18');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('5','1','2','Osteoclasis NEC',to_date('16/09/20','RR/MM/DD'),'33');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('6','6','4','Activ musculosk exer NEC',to_date('15/05/12','RR/MM/DD'),'145');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('7','4','15','Arth/pros rem wo re-shld',to_date('14/02/06','RR/MM/DD'),'134');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('8','1','15','Excis lesion of muscle',to_date('14/01/22','RR/MM/DD'),'49');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('9','5','11','Excise bone for grft NOS',to_date('14/01/29','RR/MM/DD'),'68');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('10','13','4','Excis external ear NEC',to_date('15/05/12','RR/MM/DD'),'226');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('11','5','18','Injection into marrow',to_date('17/06/07','RR/MM/DD'),'15');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('12','7','8','Drsl/drslumb fus ant/ant',to_date('15/11/16','RR/MM/DD'),'143');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('13','10','19','Culture-lower GI',to_date('14/05/19','RR/MM/DD'),'206');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('14','6','2','Fat graft to breast',to_date('17/04/17','RR/MM/DD'),'99');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('15','14','20','Total body perfusion',to_date('17/11/01','RR/MM/DD'),'192');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('16','8','1','Patellar stabilization',to_date('16/02/07','RR/MM/DD'),'61');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('17','13','14','Op red-int fix tib/fibul',to_date('15/06/18','RR/MM/DD'),'108');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('18','10','11','Periph ganglionect NEC',to_date('13/03/25','RR/MM/DD'),'119');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('19','10','18','Open reduction-femur fx',to_date('17/01/10','RR/MM/DD'),'226');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('20','13','8','Vaginoscopy',to_date('16/03/15','RR/MM/DD'),'28');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('21','7','11','Femoral sequestrectomy',to_date('14/05/16','RR/MM/DD'),'32');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('22','2','11','Patellar biopsy',to_date('17/01/12','RR/MM/DD'),'179');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('23','10','19','Correct everted punctum',to_date('14/08/31','RR/MM/DD'),'230');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('24','1','5','1 extraoc muscl resect',to_date('17/07/06','RR/MM/DD'),'15');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('25','8','9','Lower GI series',to_date('16/12/27','RR/MM/DD'),'206');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('26','12','5','Retroperiton fistulogram',to_date('14/06/27','RR/MM/DD'),'56');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('27','1','8','Head/neck ves incis NEC',to_date('14/02/04','RR/MM/DD'),'90');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('28','13','2','Micro exam-bili/panc NEC',to_date('14/05/06','RR/MM/DD'),'159');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('29','12','20','Spinal cord/meninges bx',to_date('14/11/20','RR/MM/DD'),'164');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('30','11','13','Culture-lower urinary',to_date('17/06/10','RR/MM/DD'),'103');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('31','1','10','Tonsillectomy',to_date('15/09/22','RR/MM/DD'),'46');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('32','4','14','Replace pyelostomy tube',to_date('14/09/20','RR/MM/DD'),'81');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('33','1','15','Ins intra-ansm pres mntr',to_date('15/12/07','RR/MM/DD'),'160');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('34','5','2','Remove FB lens NOS',to_date('17/01/30','RR/MM/DD'),'58');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('35','13','7','Other thyroid operations',to_date('16/02/15','RR/MM/DD'),'49');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('36','3','4','Type 5 tympanoplasty',to_date('14/09/01','RR/MM/DD'),'219');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('37','2','12','Remov intralum vag FB',to_date('17/03/11','RR/MM/DD'),'97');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('38','12','10','Open uterine biopsy',to_date('17/02/12','RR/MM/DD'),'207');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('39','14','16','Suture ext ear lac',to_date('17/09/16','RR/MM/DD'),'174');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('40','1','13','Type 5 tympanoplasty',to_date('15/03/26','RR/MM/DD'),'19');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('41','4','11','Facial bone dx proc NEC',to_date('13/10/19','RR/MM/DD'),'169');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('42','12','18','Other pyloroplasty',to_date('13/02/10','RR/MM/DD'),'174');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('43','1','20','Suture of saliv glnd lac',to_date('14/04/08','RR/MM/DD'),'228');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('44','1','2','Facial bone repair NEC',to_date('14/02/10','RR/MM/DD'),'120');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('45','8','3','Auto bone mt w purging',to_date('14/06/22','RR/MM/DD'),'15');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('46','6','12','Fit ext penile prosthes',to_date('17/03/03','RR/MM/DD'),'237');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('47','15','3','Revision of pedicle grft',to_date('15/07/27','RR/MM/DD'),'173');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('48','13','14','Prostatic operation NEC',to_date('13/04/24','RR/MM/DD'),'214');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('49','9','2','Thumb amputation',to_date('14/07/23','RR/MM/DD'),'190');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('50','13','10','Digestive tract xray NEC',to_date('15/01/25','RR/MM/DD'),'23');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('51','8','10','Lymphatic system scan',to_date('14/09/10','RR/MM/DD'),'157');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('52','15','4','Partial salpingectom NEC',to_date('16/05/18','RR/MM/DD'),'124');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('53','12','15','Open fx site debride NEC',to_date('16/12/06','RR/MM/DD'),'24');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('54','14','1','Varicose v lig-strip NOS',to_date('14/04/30','RR/MM/DD'),'217');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('55','3','7','Exchange transfusion',to_date('15/03/16','RR/MM/DD'),'166');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('56','13','1','Cystogram NEC',to_date('14/06/08','RR/MM/DD'),'47');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('57','11','15','Lap incis hern repr-grft',to_date('17/08/07','RR/MM/DD'),'23');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('58','12','13','Insert nasopharyn airway',to_date('14/11/16','RR/MM/DD'),'122');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('59','12','4','Thorac duct cannulation',to_date('16/02/18','RR/MM/DD'),'154');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('60','4','10','Perc robotic assist proc',to_date('15/09/05','RR/MM/DD'),'160');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('61','3','3','Audiometry',to_date('17/11/21','RR/MM/DD'),'162');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('62','15','19','Limb shorten-metacar/car',to_date('16/07/28','RR/MM/DD'),'21');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('63','15','5','Ther ult peripheral ves',to_date('14/06/18','RR/MM/DD'),'220');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('64','8','5','Anterior chamber op NEC',to_date('17/06/10','RR/MM/DD'),'210');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('65','15','20','Refus oth cerv post/post',to_date('14/06/16','RR/MM/DD'),'171');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('66','8','2','Replace trach tube',to_date('15/03/31','RR/MM/DD'),'138');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('67','14','17','Tooth restor by filling',to_date('14/05/15','RR/MM/DD'),'143');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('68','2','8','Trabecul carneae cord op',to_date('17/06/21','RR/MM/DD'),'173');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('69','3','12','Vaginal operation NEC',to_date('13/11/28','RR/MM/DD'),'164');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('70','9','20','Facial bone dx proc NEC',to_date('16/12/04','RR/MM/DD'),'51');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('71','12','17','Urethrotomy',to_date('17/03/23','RR/MM/DD'),'120');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('72','13','8','Appl ext fix-tib/fibula',to_date('16/10/16','RR/MM/DD'),'43');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('73','8','10','Bursotomy',to_date('14/05/23','RR/MM/DD'),'171');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('74','11','19','Cls red-tibia/fib epiphy',to_date('15/12/30','RR/MM/DD'),'15');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('75','4','2','Removal FB from hand',to_date('14/06/19','RR/MM/DD'),'232');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('76','2','16','Orthotic evaluation',to_date('14/01/03','RR/MM/DD'),'155');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('77','3','19','Intrathor lymphangiogram',to_date('17/08/22','RR/MM/DD'),'41');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('78','7','9','Trephin sclera w iridect',to_date('17/04/12','RR/MM/DD'),'187');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('79','5','20','Accessory-facial anastom',to_date('13/01/21','RR/MM/DD'),'145');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('80','12','12','Bronchoscopy thru stoma',to_date('17/11/10','RR/MM/DD'),'165');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('81','3','10','Incision of nose',to_date('17/09/19','RR/MM/DD'),'175');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('82','3','16','Presacral sympathectomy',to_date('14/12/31','RR/MM/DD'),'76');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('83','1','1','Parasitology-integument',to_date('16/06/12','RR/MM/DD'),'190');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('84','9','10','Dx aspirat-ant chamber',to_date('16/04/28','RR/MM/DD'),'180');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('85','9','15','Repair ob lac corp uteri',to_date('14/10/11','RR/MM/DD'),'100');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('86','14','7','Polio vaccine administra',to_date('15/10/25','RR/MM/DD'),'170');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('87','13','8','Ethmoidectomy',to_date('14/07/22','RR/MM/DD'),'63');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('88','6','1','Micro exam-musculosk NEC',to_date('17/07/13','RR/MM/DD'),'140');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('89','6','11','Synovectomy-site NOS',to_date('17/07/05','RR/MM/DD'),'192');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('90','13','6','Cord  repair NEC',to_date('15/04/26','RR/MM/DD'),'147');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('91','10','19','Create cutanperiton fist',to_date('13/05/22','RR/MM/DD'),'157');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('92','11','9','Revise spine theca shunt',to_date('13/12/11','RR/MM/DD'),'167');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('93','13','12','Bone marrow trnsplnt NOS',to_date('15/10/28','RR/MM/DD'),'134');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('94','9','16','Hand fasciectomy NEC',to_date('17/05/26','RR/MM/DD'),'237');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('95','4','14','Perirectal incision',to_date('13/06/19','RR/MM/DD'),'17');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('96','10','4','Cerebral scan',to_date('16/08/19','RR/MM/DD'),'117');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('97','13','3','Excise axillary node',to_date('17/06/24','RR/MM/DD'),'149');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('98','13','20','Limited rhinoplasty',to_date('13/10/15','RR/MM/DD'),'72');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('99','12','1','Opn pull-thru res rectum',to_date('13/05/05','RR/MM/DD'),'107');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('100','2','15','Cul-de-sac operation NEC',to_date('17/08/03','RR/MM/DD'),'194');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('101','8','14','Nasal operation NEC',to_date('17/11/20','RR/MM/DD'),'100');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('102','2','15','Grft rep endocar cushion',to_date('16/08/15','RR/MM/DD'),'65');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('103','13','20','Blood vessel thermograph',to_date('13/01/01','RR/MM/DD'),'29');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('104','2','8','Fit above knee prosthes',to_date('16/02/21','RR/MM/DD'),'26');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('105','1','3','Bone graft-tibia/fibula',to_date('14/10/20','RR/MM/DD'),'110');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('106','10','9','Abltn lung tiss NEC/NOS',to_date('13/12/08','RR/MM/DD'),'237');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('107','9','2','Close rectal fist NEC',to_date('13/09/14','RR/MM/DD'),'55');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('108','15','10','Eyeball enucleation NEC',to_date('17/08/07','RR/MM/DD'),'86');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('109','11','3','Arbovirus enceph vaccin',to_date('13/11/29','RR/MM/DD'),'153');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('110','5','9','Tot ostect-radius/ulna',to_date('17/07/04','RR/MM/DD'),'216');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('111','8','9','Skin excision for graft',to_date('16/02/15','RR/MM/DD'),'187');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('112','2','4','Wrist joint biopsy',to_date('17/09/13','RR/MM/DD'),'16');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('113','4','14','Open reduct tm dislocat',to_date('14/03/31','RR/MM/DD'),'119');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('114','1','16','Replace vaginal pessary',to_date('15/03/09','RR/MM/DD'),'77');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('115','15','2','Limb short proc-humerus',to_date('13/01/29','RR/MM/DD'),'98');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('116','4','17','Arthroscopy NOS',to_date('14/12/30','RR/MM/DD'),'146');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('117','13','4','Non-coronary IFVA',to_date('13/11/15','RR/MM/DD'),'116');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('118','2','20','Laparoscopic cecectomy',to_date('13/07/11','RR/MM/DD'),'29');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('119','9','6','Injection into testes',to_date('15/04/05','RR/MM/DD'),'219');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('120','1','4','Common duct exploration',to_date('15/07/12','RR/MM/DD'),'195');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('121','9','11','Mediastinal tracheostomy',to_date('13/11/02','RR/MM/DD'),'41');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('122','1','19','Repair of orbital wound',to_date('16/09/20','RR/MM/DD'),'74');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('123','8','11','Bact smear-op wound',to_date('13/07/14','RR/MM/DD'),'18');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('124','3','12','Op red-tibia/fib epiphys',to_date('15/09/17','RR/MM/DD'),'195');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('125','15','17','Loc exc bone lesion NOS',to_date('15/08/24','RR/MM/DD'),'142');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('126','4','9','Open incis hern-grft NEC',to_date('14/01/14','RR/MM/DD'),'113');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('127','1','8','Abd vein resect ',to_date('14/01/14','RR/MM/DD'),'17');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('128','12','20','Eyeball  biopsy',to_date('12/12/21','RR/MM/DD'),'32');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('129','15','19','Remove bile duct prosth',to_date('16/03/07','RR/MM/DD'),'226');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('130','1','2','Opn pull-thru res rectum',to_date('17/04/02','RR/MM/DD'),'58');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('131','12','20','Gastroscopy NEC',to_date('16/03/05','RR/MM/DD'),'31');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('132','6','18','Open reduction-femur fx',to_date('16/08/04','RR/MM/DD'),'169');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('133','11','19','Rx cornea lac w conj flp',to_date('17/07/31','RR/MM/DD'),'37');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('134','1','18','Excision foot joint NEC',to_date('15/10/22','RR/MM/DD'),'91');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('135','14','12','Soft tissue division NEC',to_date('17/11/13','RR/MM/DD'),'91');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('136','11','4','Lap abdperneal resc rec',to_date('13/08/02','RR/MM/DD'),'77');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('137','3','5','Other chest wall repair',to_date('17/05/15','RR/MM/DD'),'217');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('138','15','2','Toxicology-integument',to_date('14/11/02','RR/MM/DD'),'39');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('139','4','13','Cl reduc dislocation NEC',to_date('17/07/29','RR/MM/DD'),'193');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('140','10','2','Excision of joint NEC',to_date('14/11/14','RR/MM/DD'),'226');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('141','13','8','Oth chest cage ostectomy',to_date('15/05/30','RR/MM/DD'),'210');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('142','4','16','Pituitary gland incision',to_date('13/03/10','RR/MM/DD'),'111');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('143','5','17','Electronystagmogram',to_date('16/11/01','RR/MM/DD'),'78');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('144','7','12','Thoracic duct op NEC',to_date('17/11/03','RR/MM/DD'),'114');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('145','8','12','Lap lys periren/uret adh',to_date('16/03/28','RR/MM/DD'),'224');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('146','6','2','Ther ultrasound of heart',to_date('16/12/16','RR/MM/DD'),'20');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('147','4','15','Testicular operation NEC',to_date('15/09/22','RR/MM/DD'),'218');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('148','12','4','Lap creat esoph sphinct',to_date('14/11/22','RR/MM/DD'),'35');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('149','12','7','Other cast application',to_date('16/12/02','RR/MM/DD'),'208');
Insert into ZUR.ZADANIE (ID,PROJEKT,PRACOWNIK,OPIS,DATA,CZAS) values ('150','9','6','Oth totl excision thymus',to_date('14/04/04','RR/MM/DD'),'74');
